version: '3.9'

services:
  caddy:
    build: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - ./caddy/conf/:/etc/caddy/
      - ./caddy/data:/data
      - ./mirror/prod/:/mnt/mirror
      - caddy_config:/config
  
  mirror-update:
    build: mirror
    restart: unless-stopped
    command: supercronic crontab
    environment:
      - UP_HEARTBEAT_URL=${UP_HEARTBEAT_URL}
    volumes:
      - ./mirror/prod/:/mnt/mirror

volumes:
  caddy_config:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  web: